# Generated by Django 5.1 on 2024-12-12 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MomentHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Описание момента выполнения привычки. Напимер, После обеда или Перед сном.",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "time",
                    models.TimeField(help_text="Время, когда необходимо выполнять привычку.", verbose_name="Время"),
                ),
            ],
            options={
                "verbose_name": "Момент пивычки",
                "verbose_name_plural": "Моменты привычек",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка.",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Место, в котором необходимо выполнять привычку. Напимер, В парке или На работе.",
                        max_length=255,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания в днях, от 1 до 7 дней. По умолчанию 1 день.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Продолжительность выполнения привычки в секундах, не более 120 сек. По умолчанию 60 сек.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Продолжительность",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки. По умолчанию false. Недопустимо, если указан related_habit или award.",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "award",
                    models.TextField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения привычки. Недопустимо, если is_pleasant=true или указан related_habit.",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Создатель привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ссылка на приятную привычку (у которой is_pleasant=true), как на вознаграждение. Недопустимо, если is_pleasant=true или указан award.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="useful_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "moment",
                    models.ForeignKey(
                        help_text="Момент выполнения привычки с заголовком и временем.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moment_habits",
                        to="habits.momenthabit",
                        verbose_name="Момент привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
