# Generated by Django 5.1 on 2024-12-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="momenthabit",
            options={
                "ordering": ("time",),
                "verbose_name": "Момент пивычки",
                "verbose_name_plural": "Моменты привычек",
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="periodic_task",
            field=models.OneToOneField(
                blank=True,
                help_text="Оповещение о необходимости выполнения привычки.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_habits",
                to="django_celery_beat.periodictask",
                verbose_name="Периодическая рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="moment",
            field=models.OneToOneField(
                help_text="Момент выполнения привычки с заголовком и временем.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moment_habits",
                to="habits.momenthabit",
                verbose_name="Момент привычки",
            ),
        ),
    ]
